name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  crypto: ^3.0.7
  dio: ^5.9.0
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.3.2
  http: ^1.5.0
  logger: ^2.6.2
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  pocketbase: ^0.23.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
